var Types = {
	ARRAY: 'ArrayExpression',
	ASSIGNMENT: 'AssignmentExpression',
	BLOCK: 'BlockStatement',
	CALL: 'CallExpression',
	DECLARATION: 'VariableDeclaration',
	DECLARATOR: 'VariableDeclarator',
	EXPRESSION: 'ExpressionStatement',
	FUNCTION: 'FunctionExpression',
	FUNCTION_DECLARATION: 'FunctionDeclaration',
	IDENTIFIER: 'Identifier',
	LITERAL: 'Literal',
	IF: 'IfStatement',
	WHILE: 'WhileStatement',
	DO_WHILE: 'DoWhileStatement',
	FOR: 'ForStatement',
	TRY: 'TryStatement',
	MEMBER: 'MemberExpression',
	OBJECT: 'ObjectExpression',
	SEQUENCE: 'SequenceExpression',
	RETURN: 'ReturnStatement',
	PROGRAM: 'Program',
	THIS: 'ThisExpression'
};